version: '3'

services:
  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  node:
    build:
      context: ./node
    container_name: node
    entrypoint: wait-for db:3306 -t 40 -- 
    command: node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app/
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - node

networks:
  node-network:
    driver: bridge